In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('wowbgs2.csv')
df.sample(10)

,Battleground,Code,Faction,Class,KB,D,HK,DD,HD,Honor,Win,Lose,Rol,BE
1024,SM,SM5,Horde,Shaman,4,4,37,38664,15802,444,1.0,NaN,dps,1.0
4605,BG,BG40,Horde,Warlock,8,2,32,60682,22269,545,1.0,NaN,dps,NaN
4739,ES,ES18,Horde,Mage,5,6,32,71283,28731,309,NaN,1.0,dps,NaN
2141,BG,BG24,Alliance,Warlock,3,4,19,53599,19118,341,NaN,1.0,dps,1.0
1315,SA,SA2,Alliance,Death Knight,0,2,17,51236,82487,347,NaN,1.0,dps,1.0
1262,ES,ES3,Alliance,Warrior,6,4,42,83743,12146,771,1.0,NaN,dps,NaN
2554,AB,AB7,Alliance,Shaman,0,5,12,1939,50584,256,NaN,1.0,heal,NaN
2917,BG,BG32,Horde,Rogue,6,0,21,39651,1908,364,1.0,NaN,dps,NaN
5358,TK,TK39,Alliance,Paladin,13,1,45,214000,30619,690,1.0,NaN,dps,1.0
2321,BG,BG25,Horde,Shaman,4,0,18,28005,3528,355,1.0,NaN,dps,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5383 entries, 0 to 5382
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Battleground  5383 non-null   object
 1   Code          5383 non-null   object
 2   Faction       5383 non-null   object
 3   Class         5383 non-null   object
 4   KB            5383 non-null   int64
 5   D             5383 non-null   int64
 6   HK            5383 non-null   int64
 7   DD            5383 non-null   int64
 8   HD            5383 non-null   int64
 9   Honor         5383 non-null   int64
 10  Win           2723 non-null   float64
 11  Lose          2660 non-null   float64
 12  Rol           5383 non-null   object
 13  BE            954 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 588.9+ KB

In [4]:
df.isna().sum()

Battleground       0
Code               0
Faction            0
Class              0
KB                 0
D                  0
HK                 0
DD                 0
HD                 0
Honor              0
Win             2660
Lose            2723
Rol                0
BE              4429
dtype: int64

In [5]:
columns = ['Battleground', 'Faction', 'Class', 'Win', 'Lose', 'Rol', 'BE']
for column in columns:
    print(df[column].unique())

['WG' 'BG' 'TK' 'DG' 'AB' 'SM' 'TP' 'ES' 'SA' 'SS']
['Horde' 'Alliance']
['Hunter' 'Death Knight' 'Paladin' 'Rogue' 'Druid' 'Shaman' 'Priest'
 'Demon Hunter' 'Warlock' 'Warrior' 'Monk' 'Mage']
[ 1. nan]
[nan  1.]
['dps' 'heal']
[nan  1.]

In [6]:
df['Lose'] = df['Lose'].fillna(0)
df['Win'] = df['Win'].fillna(0)
df['BE'] = df['BE'].fillna(0)

In [7]:
df['Lose'] = df['Lose'].astype('int64')
df['Win'] = df['Win'].astype('int64')
df['BE'] = df['BE'].astype('int64')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5383 entries, 0 to 5382
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Battleground  5383 non-null   object
 1   Code          5383 non-null   object
 2   Faction       5383 non-null   object
 3   Class         5383 non-null   object
 4   KB            5383 non-null   int64
 5   D             5383 non-null   int64
 6   HK            5383 non-null   int64
 7   DD            5383 non-null   int64
 8   HD            5383 non-null   int64
 9   Honor         5383 non-null   int64
 10  Win           5383 non-null   int64
 11  Lose          5383 non-null   int64
 12  Rol           5383 non-null   object
 13  BE            5383 non-null   int64
dtypes: int64(9), object(5)
memory usage: 588.9+ KB

In [9]:
df.isna().sum()

Battleground    0
Code            0
Faction         0
Class           0
KB              0
D               0
HK              0
DD              0
HD              0
Honor           0
Win             0
Lose            0
Rol             0
BE              0
dtype: int64

In [11]:
# Class Type
class_type_mapping = {'Warrior': 'Melee', 'Demon Hunter': 'Melee', 'Death Knight': 'Melee', 'Rogue': 'Melee',
                      'Mage': 'Ranged', 'Warlock': 'Ranged', 'Priest': 'Ranged'}
df['Class Type'] = df['Class'].map(class_type_mapping).fillna('Both')

# Pets
pets_mapping = {'Hunter': 1, 'Warlock': 1, 'Death Knight': 1}
df['Pets'] = df['Class'].map(pets_mapping).fillna(0).astype('int64')

# Armor type
armor_type_mapping = {'Mage':'Cloth', 'Warlock':'Cloth', 'Priest':'Cloth', 'Rogue':'Leather', 'Druid':'Leather', 'Monk':'Leather',
                 'Demon Hunter':'Leather', 'Hunter':'Mail', 'Shaman':'Mail'}
df['Armor Type'] = df['Class'].map(armor_type_mapping).fillna('Plate')

In [12]:
df.sample(10)

,Battleground,Code,Faction,Class,KB,D,HK,DD,HD,Honor,Win,Lose,Rol,BE,Class Type,Pets,Armor Type
2291,AB,AB6,Alliance,Warrior,3,4,17,23676,9164,220,0,1,dps,0,Melee,0,Plate
1955,WG,WG24,Horde,Druid,0,2,18,40418,24118,174,0,1,dps,0,Both,0,Leather
1038,SM,SM6,Horde,Rogue,0,3,18,42584,11807,277,0,1,dps,1,Melee,0,Leather
1452,TK,TK13,Horde,Monk,0,3,47,0,176000,393,1,0,heal,0,Both,0,Leather
3217,SM,SM22,Horde,Hunter,8,1,37,67151,6595,527,1,0,dps,0,Both,1,Mail
804,TK,TK8,Horde,Warlock,2,4,9,22391,9911,130,0,1,dps,0,Ranged,1,Cloth
4165,TK,TK30,Alliance,Rogue,7,5,29,69788,12341,417,0,1,dps,0,Melee,0,Leather
2431,TP,TP13,Alliance,Warlock,1,3,7,10812,2314,253,0,1,dps,1,Ranged,1,Cloth
4207,TK,TK32,Horde,Druid,1,6,14,27170,10446,202,0,1,dps,0,Both,0,Leather
4358,WG,WG38,Horde,Hunter,3,4,16,84204,17573,170,0,1,dps,0,Both,1,Mail

In [14]:
df.to_csv('clean_data.csv', index=False)