In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('clean_data.csv')
df.sample(10)

,Battleground,Code,Faction,Class,KB,D,HK,DD,HD,Honor,Win,Lose,Rol,BE,Class Type,Pets,Armor Type
1016,SM,SM5,Horde,Demon Hunter,3,0,43,31192,11082,681,1,0,dps,1,Melee,0,Leather
2326,ES,ES6,Alliance,Mage,0,7,28,47394,3058,1095,1,0,dps,1,Ranged,0,Cloth
3812,BG,BG36,Alliance,Hunter,5,1,29,41045,3363,777,1,0,dps,0,Both,1,Mail
3840,BG,BG37,Alliance,Death Knight,3,6,22,46429,25778,299,0,1,dps,0,Melee,1,Plate
3425,BG,BG34,Alliance,Death Knight,2,0,4,19681,21962,496,1,0,dps,0,Melee,1,Plate
5105,SS,SS10,Alliance,Hunter,2,4,7,16596,5073,357,0,1,dps,0,Both,1,Mail
1000,SM,SM4,Alliance,Paladin,0,2,4,532,18877,133,0,1,heal,0,Both,0,Plate
319,WG,WG17,Alliance,Hunter,7,8,41,132000,25295,532,1,0,dps,0,Both,1,Mail
4070,SS,SS5,Alliance,Mage,3,2,19,48704,10466,474,0,1,dps,0,Ranged,0,Cloth
1446,TK,TK12,Horde,Death Knight,3,1,24,14902,25871,497,1,0,dps,0,Melee,1,Plate

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5383 entries, 0 to 5382
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Battleground  5383 non-null   object
 1   Code          5383 non-null   object
 2   Faction       5383 non-null   object
 3   Class         5383 non-null   object
 4   KB            5383 non-null   int64
 5   D             5383 non-null   int64
 6   HK            5383 non-null   int64
 7   DD            5383 non-null   int64
 8   HD            5383 non-null   int64
 9   Honor         5383 non-null   int64
 10  Win           5383 non-null   int64
 11  Lose          5383 non-null   int64
 12  Rol           5383 non-null   object
 13  BE            5383 non-null   int64
 14  Class Type    5383 non-null   object
 15  Pets          5383 non-null   int64
 16  Armor Type    5383 non-null   object
dtypes: int64(10), object(7)
memory usage: 715.1+ KB

In [4]:
df.drop(['Code'],axis=1,inplace=True)
df.drop(['Battleground'],axis=1,inplace=True)
# Usuwam te kolumny, gdyż zawiera nr bitwy oraz nazwę, które nic nie wznoszą do uczenia maszynowego.

In [5]:
df.to_csv('data_to_ml.csv', index=False)

In [6]:
df = pd.read_csv('data_to_ml.csv')
df.sample(10)

,Faction,Class,KB,D,HK,DD,HD,Honor,Win,Lose,Rol,BE,Class Type,Pets,Armor Type
4350,Horde,Warrior,4,2,11,62804,7333,120,0,1,dps,0,Melee,0,Plate
4196,Alliance,Warlock,7,3,61,87281,52407,615,1,0,dps,0,Ranged,1,Cloth
3896,Alliance,Hunter,3,1,34,75285,5092,774,1,0,dps,0,Both,1,Mail
3520,Horde,Mage,6,4,39,83233,9619,197,0,1,dps,0,Ranged,0,Cloth
576,Horde,Warrior,2,3,7,7190,72,486,1,0,dps,0,Melee,0,Plate
3049,Alliance,Hunter,1,1,6,29278,3931,170,0,1,dps,0,Both,1,Mail
1518,Horde,Shaman,0,4,45,17235,130000,396,1,0,heal,0,Both,0,Mail
1426,Alliance,Monk,0,0,38,842,54608,287,0,1,heal,0,Both,0,Leather
3735,Alliance,Hunter,2,5,63,41776,3982,477,0,1,dps,0,Both,1,Mail
3023,Horde,Warrior,8,2,34,77016,16975,513,1,0,dps,0,Melee,0,Plate